// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMPt9CUxS9Q2uqI46DyidPJha1THWqOs',
    appId: '1:618322574432:web:1d644b96617dd558c0d705',
    messagingSenderId: '618322574432',
    projectId: 'tik-tok-clone-99cbd',
    authDomain: 'tik-tok-clone-99cbd.firebaseapp.com',
    storageBucket: 'tik-tok-clone-99cbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTpBm7bUDTY6oiJ-oqD5ztcoXjn6fxNk',
    appId: '1:618322574432:android:b0098495f4a596e7c0d705',
    messagingSenderId: '618322574432',
    projectId: 'tik-tok-clone-99cbd',
    storageBucket: 'tik-tok-clone-99cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9DY3DOXl5vx2eXJP8GCyexoy1rlw-kL4',
    appId: '1:618322574432:ios:77a1f05d635edc81c0d705',
    messagingSenderId: '618322574432',
    projectId: 'tik-tok-clone-99cbd',
    storageBucket: 'tik-tok-clone-99cbd.appspot.com',
    iosClientId: '618322574432-qg0q6ml0tsgq6p9lr15nnm58mmae4qsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikTokClone',
  );
}
